FROM python:3.12-slim

WORKDIR /app

# Install build dependencies for psycopg2 / scipy
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libpq-dev curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY src/ ./src/
COPY api/ ./api/
COPY artifacts/ ./artifacts/
COPY data/processed/ ./data/processed/
COPY .env .

# Bake fallback model into the image
# (artifacts/fallback_model.joblib is generated by pipeline.py)

WORKDIR /app/api

ENV PYTHONPATH=/app/src:/app/api
ENV PYTHONUNBUFFERED=1

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
    CMD curl -f http://localhost:8000/health || exit 1

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
