"""Property intelligence ingestion and ETL primitives."""

from property_intelligence.etl import (
    build_gold,
    build_silver,
    incremental_load,
    write_bronze_snapshot,
)
from property_intelligence.sources import (
    HuggingFaceDatasetMetadata,
    HuggingFaceShardMetadata,
    build_hf_shard_manifest,
    download_hf_shards,
    fetch_parquet_footer_summary,
    fetch_hf_dataset_metadata,
    hf_resolve_url,
    parse_hf_dataset_metadata,
    write_shard_manifest,
    write_source_metadata,
)
from property_intelligence.hf_etl import (
    HFEtlSummary,
    build_hf_gold,
    normalize_hf_frame,
    run_hf_silver_gold_etl,
    write_hf_etl_summary,
)
from property_intelligence.contracts import (
    ContractCheck,
    ContractReport,
    validate_hf_layers,
    write_contract_report,
)
from property_intelligence.avm import (
    AvmMetrics,
    compute_avm_metrics,
    evaluate_price_per_m2_baselines,
    evaluate_tabular_hgb_cohort_intervals,
    evaluate_tabular_hgb_intervals,
    evaluate_tabular_hgb_avm,
    evaluate_tabular_hgb_quantile_intervals,
    make_tabular_hgb_pipeline,
    temporal_split,
    write_avm_report,
)
from property_intelligence.comparables import (
    COMPARABLE_COLUMNS,
    ComparableQuery,
    ComparableResult,
    NonGisComparableIndex,
    benchmark_comparable_queries,
    comparable_queries_from_frame,
)
from property_intelligence.lifecycle import (
    AvmAliasState,
    AvmPromotionThresholds,
    evaluate_avm_promotion,
    plan_alias_update,
    plan_rollback,
    write_lifecycle_report,
)

__all__ = [
    "build_gold",
    "build_silver",
    "incremental_load",
    "HuggingFaceDatasetMetadata",
    "HuggingFaceShardMetadata",
    "build_hf_shard_manifest",
    "download_hf_shards",
    "fetch_parquet_footer_summary",
    "fetch_hf_dataset_metadata",
    "hf_resolve_url",
    "parse_hf_dataset_metadata",
    "write_bronze_snapshot",
    "write_shard_manifest",
    "write_source_metadata",
    "HFEtlSummary",
    "build_hf_gold",
    "normalize_hf_frame",
    "run_hf_silver_gold_etl",
    "write_hf_etl_summary",
    "ContractCheck",
    "ContractReport",
    "validate_hf_layers",
    "write_contract_report",
    "AvmMetrics",
    "compute_avm_metrics",
    "evaluate_price_per_m2_baselines",
    "evaluate_tabular_hgb_cohort_intervals",
    "evaluate_tabular_hgb_intervals",
    "evaluate_tabular_hgb_avm",
    "evaluate_tabular_hgb_quantile_intervals",
    "make_tabular_hgb_pipeline",
    "temporal_split",
    "write_avm_report",
    "COMPARABLE_COLUMNS",
    "ComparableQuery",
    "ComparableResult",
    "NonGisComparableIndex",
    "benchmark_comparable_queries",
    "comparable_queries_from_frame",
    "AvmAliasState",
    "AvmPromotionThresholds",
    "evaluate_avm_promotion",
    "plan_alias_update",
    "plan_rollback",
    "write_lifecycle_report",
]
